# Basic
title: LiqCode
subtitle: 个人站
#welcome_message: <a>  </a>
# welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: 嗨，我是李球，13年开始从事iOS开发。现居深圳，正在修行中。
creator: <a>@LiqCode</a>

url: "https://liqcode.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: Visit blog

# Navigation buttons in the front page.
nav:
    # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: LiqCode
    # duoshuo:

# Social
social:
  #  weibo: onevcat
    github: LiqCode
  #  twitter: onevcat
  #  gplus: 107108267983477358170
    mail: liqiu12314@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
